# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://arunprakash.github.io/
baseurl: /
title: Arun Prakash
author: Arun Prakash
description: Personal page
avatar: profile.png
email: arunprakash.pts@gmail.com
github: arunprakash # username
twitter: arunsfriend
linkedin: arunprakash8
stackoverflow: users/2482162/arunprakash   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: arunprakashpts
google_analytics: #


# needed for travis-ci build
exclude: [vendor]
